CRUD_Dapper/Models/ErrorViewModel.cs
namespace CRUD_Dapper.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CRUD_Dapper/Models/Pessoas.cs
namespace CRUD_Dapper.Models
{
    public class Pessoas
    {
        public int PessoaID { get; set; }

        public string Nome { get; set;}

        public int Idade { get; set; }

        public float Peso { get; set;}
    }
}

CRUD_Dapper/Controllers/HomeController.cs
using CRUD_Dapper.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CRUD_Dapper.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CRUD_Dapper/Controllers/PessoasController.cs
using CRUD_Dapper.Models;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using Npgsql;
using System.Data;

namespace CRUD_Dapper.Controllers
{
    public class PessoasController : Controller
    {
        private readonly string ConnectionString = "User ID=postgres;Password=0919;Host=localhost;Port=5432;Database=PessoasDB";

        public IActionResult Index()
        {
            IDbConnection con;
            try
            {
                string selecaoQuery = "SELECT * FROM pessoas";
                con = new NpgsqlConnection(ConnectionString);
                con.Open();
                IEnumerable<Pessoas> listaPessoas = con.Query<Pessoas>(selecaoQuery).ToList();
                return View(listaPessoas);
            }
            catch (Exception ex)
            {
                throw;
            }
            
        }

        [HttpGet]
        
        public IActionResult Create()
        {
            return View();  
        }

        [HttpPost]
        public IActionResult Create(Pessoas pessoas)
        {
            if (ModelState.IsValid) {
                IDbConnection con;

                try
                {
                    string InsercaoQuery = "INSERT INTO pessoas(nome, idade, peso) VALUES(@Nome, @Idade, @Peso)";
                    con = new NpgsqlConnection(ConnectionString);
                    con.Open();
                    con.Execute(InsercaoQuery, pessoas);
                    con.Close();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    throw;
                }
            }
            return View(pessoas);
        }

        [HttpGet]

        public IActionResult Edit(int pessoaid) 
        {
            IDbConnection con;
            try
            {
                string selecaoQuery = "SELECT * FROM pessoas WHERE pessoaid = @pessoaid";
                con = new NpgsqlConnection(ConnectionString);
                con.Open();
                Pessoas pessoas = con.Query<Pessoas>(selecaoQuery).FirstOrDefault();
                con.Close();
                return View(pessoas);
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        [HttpPost]

        public IActionResult Edit(int pessoaid, Pessoas pessoas)
        {

            if (pessoaid!=pessoas.PessoaID)
                return NotFound();

            if(ModelState.IsValid)
            {
                IDbConnection con;
                try
                {
                    con = new NpgsqlConnection(ConnectionString);
                    string atualizarQuery = "UPDATE pessoas SET  Nome=@Nome, Idade=@Idade, Peso=@Peso WHERE PessoaID = @pessoaid";
                    con.Open();
                    con.Execute(atualizarQuery, pessoas);
                    con.Close();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    throw;
                }
            }
            return View(pessoas);
        }

        [HttpPost]

        public IActionResult Delete(int pessoaid)
        {
            IDbConnection con;
            try
            {
                string excluirQuery = "DELETE FROM pessoas WHERE PessoaID = @pessoaid";
                con = new NpgsqlConnection(ConnectionString);
                con.Open();
                con.ExecuteAsync(excluirQuery, new {pessoaid = @pessoaid});
                Console.WriteLine($"{pessoaid}");
                con.Close();
                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                throw;
            }

        }

    }
}

CRUD_Dapper/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CRUD_Dapper/Views/Pessoas/Create.cshtml
@model CRUD_Dapper.Models.Pessoas

@{
    ViewData["Title"] = "Nova Pessoa";
}

<h4 class="alert alert-secondary">Nova Pessoas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idade" class="control-label"></label>
                <input asp-for="Idade" class="form-control" />
                <span asp-validation-for="Idade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Peso" class="control-label"></label>
                <input asp-for="Peso" class="form-control" />
                <span asp-validation-for="Peso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-outline-success btn-sm" /> &emsp;
                <a asp-action="Index" class="btn btn-link btn-sm">Voltar</a>
            </div>
        </form>
    </div>
</div>

CRUD_Dapper/Views/Pessoas/Edit.cshtml
@model CRUD_Dapper.Models.Pessoas

@{
    ViewData["Title"] = "Atualizar " + Model.Nome;
}

<h4 class="alert alert-secondary">Atualizar @Model.Nome</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="PessoaID" type="hidden" />
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idade" class="control-label"></label>
                <input asp-for="Idade" class="form-control" />
                <span asp-validation-for="Idade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Peso" class="control-label"></label>
                <input asp-for="Peso" class="form-control" />
                <span asp-validation-for="Peso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Atualizar" class="btn btn-outline-primary btn-sm" /> &emsp;
                <a asp-action="Index" class="btn btn-link btn-sm">Voltar</a>
            </div>
        </form>
    </div>
</div>

CRUD_Dapper/Views/Pessoas/Index.cshtml
@model IEnumerable<CRUD_Dapper.Models.Pessoas>

@{
    ViewData["Title"] = "Listagem de pessoas";
}

<h4>Listagem de pessoas</h4>

<p>
    <a asp-action="Create" class="btn btn-outline-success btn-sm">Nova pessoa</a>
</p>
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PessoaID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Peso)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PessoaID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Idade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Peso)
            </td>
            <td>
                <a asp-controller="Pessoas" asp-action="Edit" asp-route-pessoaid="@item.PessoaID" class="btn btn-outline-info btn-sm">Atualizar</a> &emsp;
                <form asp-controller="Pessoas" asp-action="Delete" asp-route-pessoaid="@item.PessoaID" onclick="confirm('Prosseguir com a exclusão do usuário @item.Nome ?')">
                        <button type="submit" class="btn btn-outline-danger btn-sm">Excluir</button>
                    </form>
            </td>
        </tr>
}
    </tbody>
</table>

CRUD_Dapper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUD_Dapper</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRUD_Dapper.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRUD_Dapper</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CRUD_Dapper - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>